package clove.compiler

import clove.ast.*
import clove.dsl.World

object LoveRuntime:

  val groundLevel = 600
  val entityWidth = 50
  val entityHeight = 50

  def wrap(world: World): String =
    val regionTable = world.regions.map { r =>
      val overrides = r.handlers.flatMap(_.handles).map { (k, v) =>
        s"    ${k.toLowerCase} = ${LuaEmitter.emitExpr(v)}"
      }.mkString(",\n")
      s"""  {x = ${r.x}, y = ${r.y}, w = ${r.w}, h = ${r.h}, r = ${r.colorR}, g = ${r.colorG}, b = ${r.colorB},
         |$overrides
         |  }""".stripMargin
    }.mkString(",\n")

    val coroutines = world.entities
      .filter(_.updateScript.statements.nonEmpty)
      .map { e =>
        s"local ${e.name}Script = ${LuaEmitter.emitCoroutine(e.name, e.updateScript)}"
      }.mkString("\n")

    val taskSetup = world.entities
      .filter(_.updateScript.statements.nonEmpty)
      .map { e =>
        s"""  table.insert(tasks, {id = "${e.name}", co = ${e.name}Script, handlerStack = {}})"""
      }.mkString("\n")

    val spawnSetup = world.entities.map { e =>
      s"""  entities["${e.name}"] = {x = 0, y = 0, width = $entityWidth, height = $entityHeight, vy = 0}
         |${LuaEmitter.emitSpawnScript(e.name, e.spawnScript)}""".stripMargin
    }.mkString("\n")

    val defaultHandlerTable = world.defaultHandlers.map { h =>
      h.handles.map { (k, v) =>
        s"  ${k.toLowerCase} = ${LuaEmitter.emitExpr(v)}"
      }.mkString(",\n")
    }.mkString(",\n")


    val helperFunctions =
      s"""local function clove_getState(entityId, key)
        |  return entities[entityId] and entities[entityId][key]
        |end
        |
        |local function clove_setState(entityId, key, value)
        |  if entities[entityId] then
        |    entities[entityId][key] = value
        |  end
        |end""".stripMargin

    val effectImpls = world.customEffects.map { e =>
      s"""  ${e.name.toLowerCase} = ${LuaEmitter.emitEffectImpl(e)}"""
    }.mkString(",\n")

    val resolveFunction =
      s"""local function resolve(task, entityRegions, key, i)
        |  local taskRegions = entityRegions[task.id] or {}
        |  local stackSize = #task.handlerStack
        |  local regionSize = #taskRegions
        |  i = i or (stackSize + regionSize)
        |
        |  while i >= 1 do
        |    local entry
        |    if i > regionSize then
        |      entry = task.handlerStack[i - regionSize][key]
        |    else
        |      entry = taskRegions[i] and taskRegions[i][key]
        |    end
        |
        |    if entry ~= nil then
        |      if type(entry) == "table" and entry.propagate then
        |        local rest = resolve(task, entityRegions, key, i - 1)
        |
        |        local neutral = (entry.op == "+" or entry.op == "-") and 0.0 or 1.0
        |        local a = entry.leftVal and entry.value or (rest or neutral)
        |        local b = entry.leftVal and (rest or neutral) or entry.value
        |
        |        if entry.op == "*" then
        |          return a * b
        |        elseif entry.op == "+" then
        |          return a + b
        |        elseif entry.op == "-" then
        |          return a - b
        |        elseif entry.op == "/" then
        |          return a / b
        |        end
        |      else
        |        return entry
        |      end
        |    end
        |    i = i - 1
        |  end
        |
        |  if defaultHandlers[key] ~= nil then
        |    return defaultHandlers[key]
        |  end
        |  return nil
        |end""".stripMargin

    s"""-- Generated by Clove

local entities = {}
local tasks = {}
local GROUND = $groundLevel
local camera = {x = 0, y = 0, follow = nil, threshold = 400}

local defaultHandlers = {
$defaultHandlerTable
}

local regions = {
$regionTable
}

local uiDrawList = {}

local function checkCollision(a, b)
  if not a or not b then return false end
  return a.x < b.x + b.width and
         a.x + a.width > b.x and
         a.y < b.y + b.height and
         a.y + a.height > b.y
end

local function insideRegion(e, x, y, w, h)
  if not e then return false end
  return e.x < x + w and
         e.x + e.width > x and
         e.y < y + h and
         e.y + e.height > y
end

local function getCurrentRegions(e)
  local result = {}
  for _, region in ipairs(regions) do
    if insideRegion(e, region.x, region.y, region.w, region.h) then
      table.insert(result, region)
    end
  end
  return result
end

$resolveFunction

local function handleGravity(task, entityRegions, dt)
  local g = resolve(task, entityRegions, "gravity")
  local e = entities[task.id]
  if e then
    e.vy = (e.vy or 0) + g * dt
    e.y = e.y + e.vy
    if e.y + e.height >= GROUND then
      e.y = GROUND - e.height
      e.vy = 0
      e.grounded = true
    elseif e.y <= 0 then
      e.y = 0
      e.vy = 0
    else
      e.grounded = false
    end
  end
end

local function handleMove(task, entityRegions, a, b)
  local e = entities[task.id]
  if e then
    local dx, dy = a, b
    local mult = resolve(task, entityRegions, "move")
    if mult then
      dx = dx * mult
      dy = dy * mult
    end
    e.x = e.x + dx
    e.y = e.y + dy
  end
end

local function handleCollides(task, targetID)
  local e = entities[task.id]
  local target = entities[targetID]
  if e and target then
    return checkCollision(e, target)
  end
  return false
end

$helperFunctions


local effect_impls = {
$effectImpls
}


$coroutines

function love.load()
$spawnSetup
$taskSetup
end

function love.update(dt)
  local entityRegions = {}
  uiDrawList = {}
  for id, e in pairs(entities) do
    entityRegions[id] = getCurrentRegions(e)
  end

  for _, task in ipairs(tasks) do
    task.handlerStack = {}
    local ok, effect, a, b = coroutine.resume(task.co)

    while effect ~= nil do
      local response = nil

      if effect == "PushHandler" then
        table.insert(task.handlerStack, a)

      elseif effect == "Gravity" then
        handleGravity(task, entityRegions, dt)

      elseif effect == "Move" then
        handleMove(task, entityRegions, a, b)

      elseif effect == "Despawn" then
        entities[task.id] = nil
        task.dead = true
        break

      elseif effect == "Collides" then
        response = handleCollides(task, a)

      elseif effect == "SetState" then
        if entities[task.id] then
          entities[task.id][a] = b
        end

      elseif effect == "GetState" then
        if entities[task.id] then
          response = entities[task.id][a]
        end

      elseif effect == "Camera" then
        camera.follow = task.id

      elseif effect == "Jump" then
        local e = entities[task.id]
        if e and e.grounded then
          e.vy = -(resolve(task, entityRegions, "jump"))
          e.grounded = false
        end

      elseif effect == "ShowState" then
        local e = entities[task.id]
        if e and e[a] ~= nil then
          table.insert(uiDrawList, {label = a, value = e[a]})
        end
      else
        local effect_key = effect:lower()
        local impl = effect_impls[effect_key]
        if impl then
          local resolved = resolve(task, entityRegions, effect_key)
          impl(task.id, resolved, dt)
        else
          response = resolve(task, entityRegions, effect_key)
        end
      end

      ok, effect, a, b = coroutine.resume(task.co, response)
      if not ok then
        print("Script error in " .. task.id .. ": " .. tostring(effect))
        break
      end
    end
  end

  if camera.follow then
    local followed = entities[camera.follow]
    if followed and followed.x > camera.threshold then
      camera.x = followed.x - camera.threshold
    end
  end

  -- clean up dead tasks
  for i = #tasks, 1, -1 do
    if tasks[i].dead then
      table.remove(tasks, i)
    end
  end
end

function love.draw()
  for _, region in ipairs(regions) do
    love.graphics.setColor(region.r, region.g, region.b, 0.3)
    love.graphics.rectangle("fill", region.x - camera.x, region.y - camera.y, region.w, region.h)
    love.graphics.setColor(1.0, 1.0, 1.0, 1.0)
  end

  for name, e in pairs(entities) do
    if e then
      love.graphics.rectangle("fill", e.x - camera.x, e.y - camera.y, e.width, e.height)
    end
  end

  love.graphics.setColor(1, 1, 1, 1)
  for i, item in ipairs(uiDrawList) do
    love.graphics.print(item.label .. ": " .. tostring(item.value), 10, 10 + (i - 1) * 20)
  end

end""".stripMargin

  def writeToFile(world: World, path: os.Path): Unit =
    val lua = wrap(world)
    os.makeDir.all(path / os.up)
    os.write.over(path, lua)