package clove.compiler

import clove.ast.*
import clove.dsl.{Region, Behaviour}
import clove.dsl.worldbuilder.World

object LoveRuntime:

  val groundLevel = 600

  def wrap(world: World, hotReload: Boolean = false): String =
    val features = WorldAnalyser.analyse(world)

    // Emission helpers
    val regionTable = world.regions.zipWithIndex.map { (r, idx) =>
      val idStr = r.id.map(id => s"\"$id\"").getOrElse(s"\"region_$idx\"")

      val condStr = r.condition match
        case None       => "nil"
        case Some(expr) => s"function(globals) return ${LuaEmitter.emitExpr(expr, inCondition = true)} end"

      val (cr, cg, cb) = r.colour.getOrElse((1.0, 1.0, 1.0))

      // Common fields shared across all region types
      val commonFields =
        s"id = $idStr, x = ${r.x}, y = ${r.y}, w = ${r.w}, h = ${r.h}, " +
        s"hasColor = ${r.colour.isDefined}, r = $cr, g = $cg, b = $cb, condition = $condStr"

      r.behaviour match
        case Behaviour.Basic(handlers) =>
          val overrides = handlers.flatMap(_.handles).map { (k, v) =>
            s"${k.toLowerCase} = ${LuaEmitter.emitExpr(v)}"
          }.mkString(", ")
          val implOverrides = handlers.flatMap(_.impls).map { (k, f) =>
            s"${k.toLowerCase}_impl = ${LuaEmitter.emitImpl(f)}"
          }.mkString(", ")
          val allFields = List(overrides, implOverrides).filter(_.nonEmpty).mkString(", ")
          val hasHandlers = handlers.exists(h => h.handles.nonEmpty || h.impls.nonEmpty)
          val typeFields = s"type = \"basic\", hasHandlers = $hasHandlers" +
                            (if allFields.nonEmpty then s", $allFields" else "")
          s"  {$commonFields, $typeFields}"

        case Behaviour.Solid(oneWay) =>
          s"  {$commonFields, type = \"solid\", oneWay = $oneWay}"

        case Behaviour.Trigger(onEnter, onExit) =>
          val enterLua = LuaEmitter.emitTriggerScript(onEnter)
          val exitLua  = LuaEmitter.emitTriggerScript(onExit)
          s"""  {$commonFields, type = "trigger",
             |   onEnter = function(task_id, globals) $enterLua end,
             |   onExit  = function(task_id, globals) $exitLua end}""".stripMargin

    }.mkString(",\n")

    val globalsTable = world.initialGlobals.map { (k, v) =>
      s"  [\"$k\"] = ${LuaEmitter.emitExpr(v)}"
    }.mkString(",\n")

    val defaultHandlerTable = world.defaultHandlers.map { h =>
      val values = h.handles.map { (k, v) => s"  ${k.toLowerCase} = ${LuaEmitter.emitExpr(v)}" }
      val impls = h.impls.map { (k, f) => s"  ${k.toLowerCase}_impl = ${LuaEmitter.emitImpl(f)}" }
      (values ++ impls).mkString(",\n")
    }.mkString(",\n")

    val effectImpls = world.customEffects.map { e =>
      s"  ${e.name.toLowerCase} = ${LuaEmitter.emitImpl(e.impl)}"
    }.mkString(",\n")

    val coroutines = world.entities
      .filter(_.updateScript.statements.nonEmpty)
      .map { e => s"local ${e.name}Script = ${LuaEmitter.emitCoroutine(e.name, e.updateScript)}" }
      .mkString("\n")

    val spawnSetup = world.entities.map { e =>
      s"""  entities["${e.name}"] = {vy = 0}
         |${LuaEmitter.emitSpawnScript(e.name, e.spawnScript)}""".stripMargin
    }.mkString("\n")

    val taskSetup = world.entities
      .filter(_.updateScript.statements.nonEmpty)
      .map { e => s"""  table.insert(tasks, {id = "${e.name}", co = ${e.name}Script, handlerStack = {}})""" }
      .mkString("\n")

    val hotReloadBlock = if hotReload then
      """|local _lastModified = love.filesystem.getInfo("main.lua") and love.filesystem.getInfo("main.lua").modtime or 0
         |""".stripMargin
    else ""

    val hotReloadCheck = if hotReload then
      """|  local info = love.filesystem.getInfo("main.lua")
         |  if info and info.modtime ~= _lastModified then love.event.quit("restart") end
         |""".stripMargin
    else ""

    // Generated Lua
    val cx = if features.usesCamera then "camera.x" else "0"
    val cy = if features.usesCamera then "camera.y" else "0"

    s"""-- Generated by Clove
$hotReloadBlock
local entities = {}
local tasks    = {}
${if features.usesCamera  then "local camera = {x = 0, y = 0, follow = nil, threshold = 400}" else ""}
${if features.usesGravity then s"local GROUND = $groundLevel" else ""}

${if features.usesGlobals then s"local globals = {\n$globalsTable\n}" else ""}

local defaultHandlers = {
$defaultHandlerTable
}

local regions = {
$regionTable
}

${if features.usesShowState then "local uiDrawList = {}" else ""}
${if features.usesTriggers  then "local prevOverlap = {}" else ""}

${LuaRuntime.utilityFunctions(features)}

${if features.usesHandlers then LuaRuntime.resolveFunction else ""}

${LuaRuntime.builtinHandlers(features)}

${LuaRuntime.setSize}

${LuaRuntime.dispatchTable(features)}

local effect_impls = {
$effectImpls
}

-- Entity coroutines
$coroutines

function love.load()
$spawnSetup
$taskSetup

  for name, e in pairs(entities) do
    if e.spritePath then
      e.sprite = love.graphics.newImage(e.spritePath)
    end
${if features.usesAnimations then LuaRuntime.spritesheetLoad else ""}
  end
end

function love.update(dt)
$hotReloadCheck
${if features.usesShowState then "  uiDrawList = {}" else ""}
${if features.usesHandlers then
    """|  local entityRegions = {}
       |  for id, e in pairs(entities) do
       |    entityRegions[id] = getHandledRegions(e)
       |  end""".stripMargin
  else "  local entityRegions = {}"}

  for _, task in ipairs(tasks) do
    task.handlerStack = {}
    local ok, effect, a, b = coroutine.resume(task.co)

    while effect ~= nil do
      local response = nil

      if effect == "PushHandler" then
        table.insert(task.handlerStack, a)

      elseif effect == "Despawn" then
        entities[task.id] = nil
        task.dead = true
        break

      else
        local builtin = dispatch[effect]
        if builtin then
          response = builtin(task, entityRegions, a, b, dt)
        else
          -- Custom or query effect, check handler impl, then effect_impls, then return resolved value
          local effect_key = effect:lower()
          local resolved, handlerImpl = resolve(task, entityRegions, effect_key)
          if handlerImpl then
            handlerImpl(task.id, resolved, dt)
          else
            local impl = effect_impls[effect_key]
            if impl then impl(task.id, resolved, dt)
            else response = resolved
            end
          end
        end
      end

      ok, effect, a, b = coroutine.resume(task.co, response)
      if not ok then
        print("Script error in " .. task.id .. ": " .. tostring(effect))
        break
      end
    end
  end

${if features.usesAnimations then LuaRuntime.animUpdate else ""}
${if features.usesTriggers   then "  handleTriggers()" else ""}
${if features.usesCamera then
    """|  if camera.follow then
       |    local followed = entities[camera.follow]
       |    if followed and followed.x > camera.threshold then
       |      camera.x = followed.x - camera.threshold
       |    end
       |  end""".stripMargin
  else ""}

  for i = #tasks, 1, -1 do
    if tasks[i].dead then table.remove(tasks, i) end
  end
end

function love.draw()
  for _, region in ipairs(regions) do
    if region.hasColor and regionActive(region) then
      love.graphics.setColor(region.r, region.g, region.b, 1)
      love.graphics.rectangle("fill", region.x - $cx, region.y - $cy, region.w, region.h)
      love.graphics.setColor(1, 1, 1, 1)
    end
  end

  for name, e in pairs(entities) do
    if e then
${if features.usesAnimations then
   s"""|${LuaRuntime.animDraw}
      elseif e.sprite then""".stripMargin
  else
    "      if e.sprite then"}
        love.graphics.setColor(1, 1, 1, 1)
        love.graphics.draw(e.sprite, e.x - $cx, e.y - $cy, 0,
          e.width / e.sprite:getWidth(), e.height / e.sprite:getHeight())
      else
        love.graphics.setColor(1, 1, 1, 1)
        love.graphics.rectangle("fill", e.x - $cx, e.y - $cy, e.width, e.height)
      end
    end
  end

${if features.usesShowState then
   """|  love.graphics.setColor(1, 1, 1, 1)
  for i, item in ipairs(uiDrawList) do
    love.graphics.print(item.label .. ": " .. tostring(item.value), 10, 10 + (i - 1) * 20)
  end""".stripMargin
  else ""}
end""".stripMargin

  def writeToFile(world: World, path: os.Path, hotReload: Boolean = false): Unit =
    val lua = wrap(world, hotReload)
    os.makeDir.all(path / os.up)
    os.write.over(path, lua)
    val assetsSource = os.pwd / "src" / "main" / "resources" / "assets"
    val assetsDest = path / os.up / "assets"
    if os.exists(assetsSource) then
      os.copy.over(assetsSource, assetsDest, createFolders = true)